server:
  port: 8082

spring:
  dubbo:
    application:
      name: springboot-dubbo-consumer #应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20880 #dubbo服务暴露的端口
    scan: com.zhong.web.controller #扫描的包名
    consumer:
      check: false # 检测 dubbo 服务提供者是否存在
      retries: 0 # 远程服务调用重试次数，不包括第一次调用
