server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.8.16/shopone_test?&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: xxxxxxxxxxxxx

  dubbo:
    application:
      name: springboot-dubbo-provider #应用名
    registry:
      address: zookeeper://localhost #zookeeper地址
      port: 2181 #提供注册的端口
    protocol:
      name: dubbo
      port: 20880 #dubbo服务暴露的端口
    scan: com.zhong.service #扫描的包名

